root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o bin/app cmd/main.go"
  bin = "./bin/app"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "html", "css", "js"]
  exclude_regex = ["_test\\.go"]

[screen]
  clear_on_rebuild = true
